import type { NistBaseline } from './project.types';

export type ControlPriority = 'critical' | 'high' | 'medium' | 'low';

export interface ControlNarrative {
  control_id: string;
  family: string;
  title: string;
  default_narrative: string;
  narrative: string;
  system_implementation?: string;
  implementation_status?: string;
  isCustom: boolean;
  wasCustom?: boolean;
  enhancements?: string[];
  baselines: NistBaseline[];
  referencedDevices?: string[];
  referencedBoundaries?: string[];
  coverageStatus?: ControlCoverageStatus;
  autoGenerated?: boolean;
  autoGeneratedAt?: string;
  isApplicableToBaseline?: boolean;
  priority?: ControlPriority;
  isRecommended?: boolean;
  recommendationReason?: string;
}

export interface ControlFamily {
  code: string;
  name: string;
  controls: ControlNarrative[];
}

export type ControlCoverageStatus = 'full' | 'partial' | 'none';

