/**
 * Control Narratives Store Selectors
 *
 * Provides optimized selectors for useControlNarrativesStore using Zustand's shallow equality checking.
 * These selectors prevent unnecessary re-renders by only triggering updates when
 * the specific slice of state actually changes.
 *
 * Usage:
 * ```tsx
 * import { useControlNarrativesStore } from '@/core/stores/useControlNarrativesStore';
 * import { selectControlItems, selectControlFilters } from '@/core/stores/selectors/controlNarrativesSelectors';
 * import { useShallow } from 'zustand/react/shallow';
 *
 * // In component:
 * const { items, families } = useControlNarrativesStore(useShallow(selectControlItems));
 * ```
 */

import type { ControlFamily, ControlNarrative, NistBaseline, AppNode, AppEdge } from '@/lib/utils/types';

// Type for the control narratives state
interface ControlNarrativesState {
  items: Record<string, ControlNarrative>;
  families: ControlFamily[];
  baseline: NistBaseline;
  searchTerm: string;
  showOnlyApplicable: boolean;
  hiddenCustomCount: number;
  dirtyIds: Set<string>;
  dirtyCount: number;
  loading: boolean;
  saving: boolean;
  generating: boolean;
  generationProgress: {
    total: number;
    completed: number;
    current: string | null;
    errors: Array<{ controlId: string; error: string }>;
  } | null;
  error: string | null;
  projectId: number | null;

  // Actions
  loadControls: (params: { baseline: NistBaseline; projectId: number }) => Promise<void>;
  changeBaseline: (newBaseline: NistBaseline) => Promise<void>;
  setSearchTerm: (term: string) => void;
  setShowOnlyApplicable: (value: boolean) => void;
  updateNarrative: (controlId: string, text: string) => void;
  updateStatus: (controlId: string, status: string) => void;
  resetControl: (controlId: string) => void;
  saveNarratives: () => Promise<{ saved: number; cleared: number } | void>;
  saveSingleControl: (controlId: string) => Promise<{ success: boolean; error?: string }>;
  getNarrativesForBaseline: () => Record<string, ControlNarrative>;
  autoPopulateFromTopology: (nodes: AppNode[], edges: AppEdge[]) => Promise<void>;
  getAutoGeneratedNarrative: (
    controlId: string,
    nodes: AppNode[],
    edges: AppEdge[]
  ) => Promise<string | null>;
  generateAllWithAI: (options?: { onlyEmpty?: boolean; controlIds?: string[] }) => Promise<{ generated: number; errors: number }>;
  cancelGeneration: () => void;
}

// ==================== State Slice Selectors ====================

/**
 * Selects control items and families
 * Use for rendering the controls list
 */
export const selectControlItems = (state: ControlNarrativesState) => ({
  items: state.items,
  families: state.families,
});

/**
 * Selects only the items record
 * Use when you only need the raw control data
 */
export const selectItems = (state: ControlNarrativesState) => state.items;

/**
 * Selects only the families array
 * Use when you only need the grouped family data
 */
export const selectFamilies = (state: ControlNarrativesState) => state.families;

/**
 * Selects filter state
 * Use for filtering controls
 */
export const selectControlFilters = (state: ControlNarrativesState) => ({
  baseline: state.baseline,
  searchTerm: state.searchTerm,
  showOnlyApplicable: state.showOnlyApplicable,
});

/**
 * Selects dirty/unsaved state
 * Use for showing save indicators
 */
export const selectDirtyState = (state: ControlNarrativesState) => ({
  dirtyIds: state.dirtyIds,
  dirtyCount: state.dirtyCount,
});

/**
 * Selects loading states
 * Use for showing loading indicators
 */
export const selectLoadingStates = (state: ControlNarrativesState) => ({
  loading: state.loading,
  saving: state.saving,
  generating: state.generating,
});

/**
 * Selects generation progress
 * Use for showing AI generation progress
 */
export const selectGenerationProgress = (state: ControlNarrativesState) => ({
  generating: state.generating,
  generationProgress: state.generationProgress,
});

/**
 * Selects error state
 * Use for error display
 */
export const selectErrorState = (state: ControlNarrativesState) => ({
  error: state.error,
});

/**
 * Selects project association
 * Use when checking project context
 */
export const selectProjectContext = (state: ControlNarrativesState) => ({
  projectId: state.projectId,
  baseline: state.baseline,
});

/**
 * Selects hidden custom count
 * Use for UI indicators about hidden controls
 */
export const selectHiddenCustomCount = (state: ControlNarrativesState) => ({
  hiddenCustomCount: state.hiddenCustomCount,
});

// ==================== Action Selectors ====================

/**
 * Selects loading actions
 * Use for loading/changing controls
 */
export const selectLoadActions = (state: ControlNarrativesState) => ({
  loadControls: state.loadControls,
  changeBaseline: state.changeBaseline,
});

/**
 * Selects filter actions
 * Use for filtering UI
 */
export const selectFilterActions = (state: ControlNarrativesState) => ({
  setSearchTerm: state.setSearchTerm,
  setShowOnlyApplicable: state.setShowOnlyApplicable,
});

/**
 * Selects narrative mutation actions
 * Use for editing individual controls
 */
export const selectNarrativeActions = (state: ControlNarrativesState) => ({
  updateNarrative: state.updateNarrative,
  updateStatus: state.updateStatus,
  resetControl: state.resetControl,
});

/**
 * Selects save actions
 * Use for saving changes
 */
export const selectSaveActions = (state: ControlNarrativesState) => ({
  saveNarratives: state.saveNarratives,
  saveSingleControl: state.saveSingleControl,
});

/**
 * Selects AI generation actions
 * Use for AI-powered narrative generation
 */
export const selectAIActions = (state: ControlNarrativesState) => ({
  autoPopulateFromTopology: state.autoPopulateFromTopology,
  getAutoGeneratedNarrative: state.getAutoGeneratedNarrative,
  generateAllWithAI: state.generateAllWithAI,
  cancelGeneration: state.cancelGeneration,
});

/**
 * Selects getter actions
 * Use for reading narratives
 */
export const selectGetterActions = (state: ControlNarrativesState) => ({
  getNarrativesForBaseline: state.getNarrativesForBaseline,
});

// ==================== Combined Selectors for Common Use Cases ====================

/**
 * Selector for ControlCard component
 * Commonly used actions for individual control editing
 */
export const selectControlCardActions = (state: ControlNarrativesState) => ({
  updateNarrative: state.updateNarrative,
  updateStatus: state.updateStatus,
  resetControl: state.resetControl,
  saveSingleControl: state.saveSingleControl,
});

/**
 * Selector for ControlCard state
 */
export const selectControlCardState = (state: ControlNarrativesState) => ({
  dirtyIds: state.dirtyIds,
  saving: state.saving,
});

/**
 * Selector for ControlNarrativesPanel
 * Main panel state and actions
 */
export const selectControlPanelState = (state: ControlNarrativesState) => ({
  items: state.items,
  families: state.families,
  baseline: state.baseline,
  searchTerm: state.searchTerm,
  showOnlyApplicable: state.showOnlyApplicable,
  loading: state.loading,
  error: state.error,
  dirtyCount: state.dirtyCount,
});

/**
 * Selector for ControlNarrativesPanel actions
 */
export const selectControlPanelActions = (state: ControlNarrativesState) => ({
  loadControls: state.loadControls,
  changeBaseline: state.changeBaseline,
  setSearchTerm: state.setSearchTerm,
  setShowOnlyApplicable: state.setShowOnlyApplicable,
  saveNarratives: state.saveNarratives,
  autoPopulateFromTopology: state.autoPopulateFromTopology,
});

/**
 * Selector for ControlCoveragePanel
 * Used in the coverage display component
 */
export const selectControlCoverageState = (state: ControlNarrativesState) => ({
  items: state.items,
  baseline: state.baseline,
});

/**
 * Selector for AI Generation UI
 */
export const selectAIGenerationState = (state: ControlNarrativesState) => ({
  generating: state.generating,
  generationProgress: state.generationProgress,
  error: state.error,
});

/**
 * Selector for AI Generation UI actions
 */
export const selectAIGenerationActions = (state: ControlNarrativesState) => ({
  generateAllWithAI: state.generateAllWithAI,
  cancelGeneration: state.cancelGeneration,
});
