/**
 * Unified Compliance Store
 *
 * This store provides a unified interface to compliance-related functionality
 * while maintaining backward compatibility with existing stores.
 *
 * The consolidation provides:
 * - Single import point for all compliance functionality
 * - Unified selectors and actions
 * - Clear ownership of compliance-related state
 * - Simplified mental model (5 stores → 1 facade)
 *
 * Original stores (for reference/migration):
 * - useControlNarrativesStore: Control implementations and narratives
 * - useControlSelectionStore: Control selection state
 * - useSSPMetadataStore: SSP metadata and persistence
 * - useSSPTemplateStore: SSP template management
 * - useOrganizationDefaultsStore: Organization defaults
 */

import { useControlNarrativesStore } from './useControlNarrativesStore';
import { useControlSelectionStore } from './useControlSelectionStore';
import { useSSPMetadataStore } from './sspMetadataStore';
import { useSSPTemplateStore } from './useSSPTemplateStore';
import { useOrganizationDefaultsStore } from './useOrganizationDefaultsStore';

// Re-export individual stores for backward compatibility
export { useControlNarrativesStore } from './useControlNarrativesStore';
export { useControlSelectionStore } from './useControlSelectionStore';
export { useSSPMetadataStore } from './sspMetadataStore';
export { useSSPTemplateStore } from './useSSPTemplateStore';
export { useOrganizationDefaultsStore } from './useOrganizationDefaultsStore';

/**
 * Unified Compliance Store Hook
 *
 * Provides a single access point to all compliance-related state and actions.
 * This is the recommended way to access compliance functionality.
 *
 * @example
 * ```tsx
 * const {
 *   // Control narratives
 *   controls, loadControls, updateNarrative,
 *   // Control selection
 *   selectedControlIds, toggleControl,
 *   // SSP metadata
 *   sspMetadata, saveSSP,
 *   // Templates
 *   templates, applyTemplate
 * } = useComplianceStore();
 * ```
 */
export function useComplianceStore() {
  // Control narratives from useControlNarrativesStore
  const narrativesState = useControlNarrativesStore();

  // Control selection from useControlSelectionStore
  const selectionState = useControlSelectionStore();

  // SSP metadata from useSSPMetadataStore
  const sspState = useSSPMetadataStore();

  // Templates from useSSPTemplateStore
  const templateState = useSSPTemplateStore();

  // Organization defaults from useOrganizationDefaultsStore
  const orgDefaultsState = useOrganizationDefaultsStore();

  return {
    // ===== Control Narratives (from useControlNarrativesStore) =====
    controls: narrativesState.items,
    controlFamilies: narrativesState.families,
    controlBaseline: narrativesState.baseline,
    controlSearchTerm: narrativesState.searchTerm,
    showOnlyApplicable: narrativesState.showOnlyApplicable,
    controlDirtyIds: narrativesState.dirtyIds,
    controlDirtyCount: narrativesState.dirtyCount,
    controlsLoading: narrativesState.loading,
    controlsSaving: narrativesState.saving,
    controlsGenerating: narrativesState.generating,
    generationProgress: narrativesState.generationProgress,
    controlsError: narrativesState.error,
    controlProjectId: narrativesState.projectId,

    // Control narrative actions
    loadControls: narrativesState.loadControls,
    changeBaseline: narrativesState.changeBaseline,
    setControlSearchTerm: narrativesState.setSearchTerm,
    setShowOnlyApplicable: narrativesState.setShowOnlyApplicable,
    updateControlNarrative: narrativesState.updateNarrative,
    updateControlStatus: narrativesState.updateStatus,
    resetControl: narrativesState.resetControl,
    saveNarratives: narrativesState.saveNarratives,
    saveSingleControl: narrativesState.saveSingleControl,
    getNarrativesForBaseline: narrativesState.getNarrativesForBaseline,
    autoPopulateFromTopology: narrativesState.autoPopulateFromTopology,
    getAutoGeneratedNarrative: narrativesState.getAutoGeneratedNarrative,
    generateAllWithAI: narrativesState.generateAllWithAI,
    cancelGeneration: narrativesState.cancelGeneration,

    // ===== Control Selection (from useControlSelectionStore) =====
    selectedControlIds: selectionState.selectedControlIds,
    selectionInitialized: selectionState.initialized,

    // Selection actions
    setSelectedControlIds: selectionState.setSelectedControlIds,
    toggleControl: selectionState.toggleControl,
    selectByPriority: selectionState.selectByPriority,
    selectAllControls: selectionState.selectAll,
    clearAllControls: selectionState.clearAll,
    applyRecommendations: selectionState.applyRecommendations,
    initializeSmartDefaults: selectionState.initializeSmartDefaults,
    isControlSelected: selectionState.isSelected,
    getSelectedCount: selectionState.getSelectedCount,

    // ===== SSP Metadata (from useSSPMetadataStore) =====
    sspMetadata: sspState.metadata,
    selectedControlFamilies: sspState.selectedControlFamilies,
    sspIsDirty: sspState.isDirty,

    // SSP metadata actions
    setSSPMetadata: sspState.setMetadata,
    updateSSPMetadata: sspState.updateMetadata,
    setSelectedControlFamilies: sspState.setSelectedControlFamilies,
    loadSSPMetadata: sspState.loadMetadata,
    saveSSPMetadata: sspState.saveMetadata,
    resetSSPMetadata: sspState.resetMetadata,
    setSSPDirty: sspState.setDirty,
    addCustomSection: sspState.addCustomSection,
    updateCustomSection: sspState.updateCustomSection,
    deleteCustomSection: sspState.deleteCustomSection,

    // ===== SSP Templates (from useSSPTemplateStore) =====
    templates: templateState.templates,
    selectedTemplateId: templateState.selectedTemplateId,

    // Template actions
    addTemplate: templateState.addTemplate,
    updateTemplate: templateState.updateTemplate,
    deleteTemplate: templateState.deleteTemplate,
    getTemplate: templateState.getTemplate,
    selectTemplate: templateState.selectTemplate,
    createTemplateFromMetadata: templateState.createFromMetadata,
    applyTemplate: templateState.applyTemplate,
    getSortedTemplates: templateState.getSortedTemplates,

    // ===== Organization Defaults (from useOrganizationDefaultsStore) =====
    orgDefaults: orgDefaultsState.defaults,
    orgDefaultsLastUpdated: orgDefaultsState.lastUpdated,

    // Organization defaults actions
    setOrgDefaults: orgDefaultsState.setDefaults,
    updateOrgDefaults: orgDefaultsState.updateDefaults,
    resetOrgDefaults: orgDefaultsState.resetDefaults,
    getSSPDefaults: orgDefaultsState.getSSPDefaults,
    importFromSSPMetadata: orgDefaultsState.importFromSSPMetadata,
  };
}

// ============================================================================
// Selectors for granular subscriptions
// ============================================================================

/**
 * Selector for control selection only
 */
export const useSelectedControls = () => {
  const selectedControlIds = useControlSelectionStore((state) => state.selectedControlIds);
  const count = useControlSelectionStore((state) => state.getSelectedCount());
  return { selectedControlIds, count };
};

/**
 * Selector for control narrative by ID
 */
export const useControlNarrative = (controlId: string) => {
  return useControlNarrativesStore((state) => state.items[controlId]);
};

/**
 * Selector for control loading state
 */
export const useControlLoadingState = () => {
  return useControlNarrativesStore((state) => ({
    loading: state.loading,
    saving: state.saving,
    generating: state.generating,
    error: state.error,
  }));
};

/**
 * Selector for SSP metadata only
 */
export const useSSPState = () => {
  return useSSPMetadataStore((state) => ({
    metadata: state.metadata,
    isDirty: state.isDirty,
  }));
};

/**
 * Selector for templates list
 */
export const useTemplatesList = () => {
  return useSSPTemplateStore((state) => state.getSortedTemplates());
};

/**
 * Selector for generation progress
 */
export const useGenerationProgress = () => {
  return useControlNarrativesStore((state) => ({
    generating: state.generating,
    progress: state.generationProgress,
  }));
};

// ============================================================================
// Static access for non-React contexts
// ============================================================================

/**
 * Get the current state of all compliance stores (non-reactive)
 */
export const getComplianceState = () => ({
  narratives: useControlNarrativesStore.getState(),
  selection: useControlSelectionStore.getState(),
  ssp: useSSPMetadataStore.getState(),
  templates: useSSPTemplateStore.getState(),
  orgDefaults: useOrganizationDefaultsStore.getState(),
});

/**
 * Load controls for a project
 */
export const loadControlsForProject = async (projectId: number, baseline: 'LOW' | 'MODERATE' | 'HIGH') => {
  await useControlNarrativesStore.getState().loadControls({ baseline, projectId });
};

/**
 * Save all pending narrative changes
 */
export const saveAllNarratives = async () => {
  return await useControlNarrativesStore.getState().saveNarratives();
};

/**
 * Get selected control count
 */
export const getSelectedControlCount = () => {
  return useControlSelectionStore.getState().getSelectedCount();
};
