#!/usr/bin/env tsx
/**
 * Apply Pre-computed Template Layouts
 *
 * This script updates sampleProjects.ts with the positions generated by layout-templates.ts
 *
 * Usage:
 *   npm run layout:templates          # Generate positions
 *   npm run layout:templates:apply    # Apply to sampleProjects.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LAYOUTED_FILE = path.join(__dirname, '../.data/layouted-templates.json');
const SAMPLE_PROJECTS_FILE = path.join(__dirname, '../src/lib/samples/sampleProjects.ts');

function main() {
  console.log('📝 Applying pre-computed layouts to sampleProjects.ts...\n');

  // Read layouted templates
  if (!fs.existsSync(LAYOUTED_FILE)) {
    console.error('❌ Error: No layouted templates found!');
    console.error('   Run "npm run layout:templates" first.');
    process.exit(1);
  }

  const layoutedTemplates = JSON.parse(fs.readFileSync(LAYOUTED_FILE, 'utf-8'));
  console.log(`✅ Loaded ${layoutedTemplates.length} layouted templates`);

  // Read current sampleProjects.ts
  let content = fs.readFileSync(SAMPLE_PROJECTS_FILE, 'utf-8');

  // Create backup
  const backupFile = SAMPLE_PROJECTS_FILE + '.backup';
  fs.writeFileSync(backupFile, content);
  console.log(`💾 Backup created: ${path.basename(backupFile)}`);

  // Build position map for each template
  for (const template of layoutedTemplates) {
    console.log(`\n🔧 Updating positions for: ${template.name}`);

    let updateCount = 0;

    for (const node of template.nodes) {
      const { x, y } = node.position;

      // Find and replace position for this node ID
      // Look for pattern: position: { x: NUMBER, y: NUMBER }
      // after id: generateId('device-sample-1', ...)

      const idPattern = node.id.replace(/^(\w+)-sample-(\d+)$/, "$1', $2");
      const positionRegex = new RegExp(
        `(id: generateId\\('${idPattern}\\),\\s*type: '${node.type}',\\s*)position: \\{ x: \\d+, y: \\d+ \\}`,
        'g'
      );

      const replacement = `$1position: { x: ${x}, y: ${y} }`;
      const newContent = content.replace(positionRegex, replacement);

      if (newContent !== content) {
        updateCount++;
        content = newContent;
      }
    }

    console.log(`  ✓ Updated ${updateCount} node positions`);
  }

  // Write updated file
  fs.writeFileSync(SAMPLE_PROJECTS_FILE, content);
  console.log(`\n✅ Successfully updated ${SAMPLE_PROJECTS_FILE}`);
  console.log('\n📝 Summary:');
  console.log('  - Backup saved to:', path.basename(backupFile));
  console.log('  - Positions updated in sampleProjects.ts');
  console.log('  - Run "npm run build" to test the changes');
}

main();
